server:
  port: 12140
  error:
    whitelabel:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:32773/Eviant?useSSL=false
    password: password
    username: user
    tomcat:
      test-on-borrow: true
      validation-query: select 1

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
      user:
        name: user
        password: password
  flyway:
    url: jdbc:mysql://localhost:32773/Eviant?useSSL=false
    user: user
    password: password
    validate-on-migrate: true
    enabled: true
    #baseline-on-migrate: true


